//! Mathematical alphanumeric variants from LyX 2.5 `unicode_alphanum_variants` (DL153).

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum MathAlphanumVariant {
    Bold,
    Italic,
    BoldItalic,
    Script,
    BoldScript,
    Fraktur,
    BoldFraktur,
    DoubleStruck,
    Sans,
    BoldSans,
    ItalicSans,
    BoldItalicSans,
    Monospace,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MathAlphanumRow {
    pub bold: Option<&'static str>,
    pub italic: Option<&'static str>,
    pub bold_italic: Option<&'static str>,
    pub script: Option<&'static str>,
    pub bold_script: Option<&'static str>,
    pub fraktur: Option<&'static str>,
    pub bold_fraktur: Option<&'static str>,
    pub double_struck: Option<&'static str>,
    pub sans: Option<&'static str>,
    pub bold_sans: Option<&'static str>,
    pub italic_sans: Option<&'static str>,
    pub bold_italic_sans: Option<&'static str>,
    pub monospace: Option<&'static str>,
}

pub(crate) static MATH_ALPHANUM: &[(&str, MathAlphanumRow)] = &[
    (
        "a",
        MathAlphanumRow {
            bold: Some("𝐚"),
            italic: Some("𝑎"),
            bold_italic: Some("𝒂"),
            script: Some("𝒶"),
            bold_script: Some("𝓪"),
            fraktur: Some("𝔞"),
            bold_fraktur: Some("𝖆"),
            double_struck: Some("𝕒"),
            sans: Some("𝖺"),
            bold_sans: Some("𝗮"),
            italic_sans: Some("𝘢"),
            bold_italic_sans: Some("𝙖"),
            monospace: Some("𝚊"),
        },
    ),
    (
        "b",
        MathAlphanumRow {
            bold: Some("𝐛"),
            italic: Some("𝑏"),
            bold_italic: Some("𝒃"),
            script: Some("𝒷"),
            bold_script: Some("𝓫"),
            fraktur: Some("𝔟"),
            bold_fraktur: Some("𝖇"),
            double_struck: Some("𝕓"),
            sans: Some("𝖻"),
            bold_sans: Some("𝗯"),
            italic_sans: Some("𝘣"),
            bold_italic_sans: Some("𝙗"),
            monospace: Some("𝚋"),
        },
    ),
    (
        "c",
        MathAlphanumRow {
            bold: Some("𝐜"),
            italic: Some("𝑐"),
            bold_italic: Some("𝒄"),
            script: Some("𝒸"),
            bold_script: Some("𝓬"),
            fraktur: Some("𝔠"),
            bold_fraktur: Some("𝖈"),
            double_struck: Some("𝕔"),
            sans: Some("𝖼"),
            bold_sans: Some("𝗰"),
            italic_sans: Some("𝘤"),
            bold_italic_sans: Some("𝙘"),
            monospace: Some("𝚌"),
        },
    ),
    (
        "d",
        MathAlphanumRow {
            bold: Some("𝐝"),
            italic: Some("𝑑"),
            bold_italic: Some("𝒅"),
            script: Some("𝒹"),
            bold_script: Some("𝓭"),
            fraktur: Some("𝔡"),
            bold_fraktur: Some("𝖉"),
            double_struck: Some("𝕕"),
            sans: Some("𝖽"),
            bold_sans: Some("𝗱"),
            italic_sans: Some("𝘥"),
            bold_italic_sans: Some("𝙙"),
            monospace: Some("𝚍"),
        },
    ),
    (
        "e",
        MathAlphanumRow {
            bold: Some("𝐞"),
            italic: Some("𝑒"),
            bold_italic: Some("𝒆"),
            script: Some("ℯ"),
            bold_script: Some("𝓮"),
            fraktur: Some("𝔢"),
            bold_fraktur: Some("𝖊"),
            double_struck: Some("𝕖"),
            sans: Some("𝖾"),
            bold_sans: Some("𝗲"),
            italic_sans: Some("𝘦"),
            bold_italic_sans: Some("𝙚"),
            monospace: Some("𝚎"),
        },
    ),
    (
        "f",
        MathAlphanumRow {
            bold: Some("𝐟"),
            italic: Some("𝑓"),
            bold_italic: Some("𝒇"),
            script: Some("𝒻"),
            bold_script: Some("𝓯"),
            fraktur: Some("𝔣"),
            bold_fraktur: Some("𝖋"),
            double_struck: Some("𝕗"),
            sans: Some("𝖿"),
            bold_sans: Some("𝗳"),
            italic_sans: Some("𝘧"),
            bold_italic_sans: Some("𝙛"),
            monospace: Some("𝚏"),
        },
    ),
    (
        "g",
        MathAlphanumRow {
            bold: Some("𝐠"),
            italic: Some("𝑔"),
            bold_italic: Some("𝒈"),
            script: Some("ℊ"),
            bold_script: Some("𝓰"),
            fraktur: Some("𝔤"),
            bold_fraktur: Some("𝖌"),
            double_struck: Some("𝕘"),
            sans: Some("𝗀"),
            bold_sans: Some("𝗴"),
            italic_sans: Some("𝘨"),
            bold_italic_sans: Some("𝙜"),
            monospace: Some("𝚐"),
        },
    ),
    (
        "h",
        MathAlphanumRow {
            bold: Some("𝐡"),
            italic: Some("ℎ"),
            bold_italic: Some("𝒉"),
            script: Some("𝒽"),
            bold_script: Some("𝓱"),
            fraktur: Some("𝔥"),
            bold_fraktur: Some("𝖍"),
            double_struck: Some("𝕙"),
            sans: Some("𝗁"),
            bold_sans: Some("𝗵"),
            italic_sans: Some("𝘩"),
            bold_italic_sans: Some("𝙝"),
            monospace: Some("𝚑"),
        },
    ),
    (
        "i",
        MathAlphanumRow {
            bold: Some("𝐢"),
            italic: Some("𝑖"),
            bold_italic: Some("𝒊"),
            script: Some("𝒾"),
            bold_script: Some("𝓲"),
            fraktur: Some("𝔦"),
            bold_fraktur: Some("𝖎"),
            double_struck: Some("𝕚"),
            sans: Some("𝗂"),
            bold_sans: Some("𝗶"),
            italic_sans: Some("𝘪"),
            bold_italic_sans: Some("𝙞"),
            monospace: Some("𝚒"),
        },
    ),
    (
        "j",
        MathAlphanumRow {
            bold: Some("𝐣"),
            italic: Some("𝑗"),
            bold_italic: Some("𝒋"),
            script: Some("𝒿"),
            bold_script: Some("𝓳"),
            fraktur: Some("𝔧"),
            bold_fraktur: Some("𝖏"),
            double_struck: Some("𝕛"),
            sans: Some("𝗃"),
            bold_sans: Some("𝗷"),
            italic_sans: Some("𝘫"),
            bold_italic_sans: Some("𝙟"),
            monospace: Some("𝚓"),
        },
    ),
    (
        "k",
        MathAlphanumRow {
            bold: Some("𝐤"),
            italic: Some("𝑘"),
            bold_italic: Some("𝒌"),
            script: Some("𝓀"),
            bold_script: Some("𝓴"),
            fraktur: Some("𝔨"),
            bold_fraktur: Some("𝖐"),
            double_struck: Some("𝕜"),
            sans: Some("𝗄"),
            bold_sans: Some("𝗸"),
            italic_sans: Some("𝘬"),
            bold_italic_sans: Some("𝙠"),
            monospace: Some("𝚔"),
        },
    ),
    (
        "l",
        MathAlphanumRow {
            bold: Some("𝐥"),
            italic: Some("𝑙"),
            bold_italic: Some("𝒍"),
            script: Some("𝓁"),
            bold_script: Some("𝓵"),
            fraktur: Some("𝔩"),
            bold_fraktur: Some("𝖑"),
            double_struck: Some("𝕝"),
            sans: Some("𝗅"),
            bold_sans: Some("𝗹"),
            italic_sans: Some("𝘭"),
            bold_italic_sans: Some("𝙡"),
            monospace: Some("𝚕"),
        },
    ),
    (
        "m",
        MathAlphanumRow {
            bold: Some("𝐦"),
            italic: Some("𝑚"),
            bold_italic: Some("𝒎"),
            script: Some("𝓂"),
            bold_script: Some("𝓶"),
            fraktur: Some("𝔪"),
            bold_fraktur: Some("𝖒"),
            double_struck: Some("𝕞"),
            sans: Some("𝗆"),
            bold_sans: Some("𝗺"),
            italic_sans: Some("𝘮"),
            bold_italic_sans: Some("𝙢"),
            monospace: Some("𝚖"),
        },
    ),
    (
        "n",
        MathAlphanumRow {
            bold: Some("𝐧"),
            italic: Some("𝑛"),
            bold_italic: Some("𝒏"),
            script: Some("𝓃"),
            bold_script: Some("𝓷"),
            fraktur: Some("𝔫"),
            bold_fraktur: Some("𝖓"),
            double_struck: Some("𝕟"),
            sans: Some("𝗇"),
            bold_sans: Some("𝗻"),
            italic_sans: Some("𝘯"),
            bold_italic_sans: Some("𝙣"),
            monospace: Some("𝚗"),
        },
    ),
    (
        "o",
        MathAlphanumRow {
            bold: Some("𝐨"),
            italic: Some("𝑜"),
            bold_italic: Some("𝒐"),
            script: Some("ℴ"),
            bold_script: Some("𝓸"),
            fraktur: Some("𝔬"),
            bold_fraktur: Some("𝖔"),
            double_struck: Some("𝕠"),
            sans: Some("𝗈"),
            bold_sans: Some("𝗼"),
            italic_sans: Some("𝘰"),
            bold_italic_sans: Some("𝙤"),
            monospace: Some("𝚘"),
        },
    ),
    (
        "p",
        MathAlphanumRow {
            bold: Some("𝐩"),
            italic: Some("𝑝"),
            bold_italic: Some("𝒑"),
            script: Some("𝓅"),
            bold_script: Some("𝓹"),
            fraktur: Some("𝔭"),
            bold_fraktur: Some("𝖕"),
            double_struck: Some("𝕡"),
            sans: Some("𝗉"),
            bold_sans: Some("𝗽"),
            italic_sans: Some("𝘱"),
            bold_italic_sans: Some("𝙥"),
            monospace: Some("𝚙"),
        },
    ),
    (
        "q",
        MathAlphanumRow {
            bold: Some("𝐪"),
            italic: Some("𝑞"),
            bold_italic: Some("𝒒"),
            script: Some("𝓆"),
            bold_script: Some("𝓺"),
            fraktur: Some("𝔮"),
            bold_fraktur: Some("𝖖"),
            double_struck: Some("𝕢"),
            sans: Some("𝗊"),
            bold_sans: Some("𝗾"),
            italic_sans: Some("𝘲"),
            bold_italic_sans: Some("𝙦"),
            monospace: Some("𝚚"),
        },
    ),
    (
        "r",
        MathAlphanumRow {
            bold: Some("𝐫"),
            italic: Some("𝑟"),
            bold_italic: Some("𝒓"),
            script: Some("𝓇"),
            bold_script: Some("𝓻"),
            fraktur: Some("𝔯"),
            bold_fraktur: Some("𝖗"),
            double_struck: Some("𝕣"),
            sans: Some("𝗋"),
            bold_sans: Some("𝗿"),
            italic_sans: Some("𝘳"),
            bold_italic_sans: Some("𝙧"),
            monospace: Some("𝚛"),
        },
    ),
    (
        "s",
        MathAlphanumRow {
            bold: Some("𝐬"),
            italic: Some("𝑠"),
            bold_italic: Some("𝒔"),
            script: Some("𝓈"),
            bold_script: Some("𝓼"),
            fraktur: Some("𝔰"),
            bold_fraktur: Some("𝖘"),
            double_struck: Some("𝕤"),
            sans: Some("𝗌"),
            bold_sans: Some("𝘀"),
            italic_sans: Some("𝘴"),
            bold_italic_sans: Some("𝙨"),
            monospace: Some("𝚜"),
        },
    ),
    (
        "t",
        MathAlphanumRow {
            bold: Some("𝐭"),
            italic: Some("𝑡"),
            bold_italic: Some("𝒕"),
            script: Some("𝓉"),
            bold_script: Some("𝓽"),
            fraktur: Some("𝔱"),
            bold_fraktur: Some("𝖙"),
            double_struck: Some("𝕥"),
            sans: Some("𝗍"),
            bold_sans: Some("𝘁"),
            italic_sans: Some("𝘵"),
            bold_italic_sans: Some("𝙩"),
            monospace: Some("𝚝"),
        },
    ),
    (
        "u",
        MathAlphanumRow {
            bold: Some("𝐮"),
            italic: Some("𝑢"),
            bold_italic: Some("𝒖"),
            script: Some("𝓊"),
            bold_script: Some("𝓾"),
            fraktur: Some("𝔲"),
            bold_fraktur: Some("𝖚"),
            double_struck: Some("𝕦"),
            sans: Some("𝗎"),
            bold_sans: Some("𝘂"),
            italic_sans: Some("𝘶"),
            bold_italic_sans: Some("𝙪"),
            monospace: Some("𝚞"),
        },
    ),
    (
        "v",
        MathAlphanumRow {
            bold: Some("𝐯"),
            italic: Some("𝑣"),
            bold_italic: Some("𝒗"),
            script: Some("𝓋"),
            bold_script: Some("𝓿"),
            fraktur: Some("𝔳"),
            bold_fraktur: Some("𝖛"),
            double_struck: Some("𝕧"),
            sans: Some("𝗏"),
            bold_sans: Some("𝘃"),
            italic_sans: Some("𝘷"),
            bold_italic_sans: Some("𝙫"),
            monospace: Some("𝚟"),
        },
    ),
    (
        "w",
        MathAlphanumRow {
            bold: Some("𝐰"),
            italic: Some("𝑤"),
            bold_italic: Some("𝒘"),
            script: Some("𝓌"),
            bold_script: Some("𝔀"),
            fraktur: Some("𝔴"),
            bold_fraktur: Some("𝖜"),
            double_struck: Some("𝕨"),
            sans: Some("𝗐"),
            bold_sans: Some("𝘄"),
            italic_sans: Some("𝘸"),
            bold_italic_sans: Some("𝙬"),
            monospace: Some("𝚠"),
        },
    ),
    (
        "x",
        MathAlphanumRow {
            bold: Some("𝐱"),
            italic: Some("𝑥"),
            bold_italic: Some("𝒙"),
            script: Some("𝓍"),
            bold_script: Some("𝔁"),
            fraktur: Some("𝔵"),
            bold_fraktur: Some("𝖝"),
            double_struck: Some("𝕩"),
            sans: Some("𝗑"),
            bold_sans: Some("𝘅"),
            italic_sans: Some("𝘹"),
            bold_italic_sans: Some("𝙭"),
            monospace: Some("𝚡"),
        },
    ),
    (
        "y",
        MathAlphanumRow {
            bold: Some("𝐲"),
            italic: Some("𝑦"),
            bold_italic: Some("𝒚"),
            script: Some("𝓎"),
            bold_script: Some("𝔂"),
            fraktur: Some("𝔶"),
            bold_fraktur: Some("𝖞"),
            double_struck: Some("𝕪"),
            sans: Some("𝗒"),
            bold_sans: Some("𝘆"),
            italic_sans: Some("𝘺"),
            bold_italic_sans: Some("𝙮"),
            monospace: Some("𝚢"),
        },
    ),
    (
        "z",
        MathAlphanumRow {
            bold: Some("𝐳"),
            italic: Some("𝑧"),
            bold_italic: Some("𝒛"),
            script: Some("𝓏"),
            bold_script: Some("𝔃"),
            fraktur: Some("𝔷"),
            bold_fraktur: Some("𝖟"),
            double_struck: Some("𝕫"),
            sans: Some("𝗓"),
            bold_sans: Some("𝘇"),
            italic_sans: Some("𝘻"),
            bold_italic_sans: Some("𝙯"),
            monospace: Some("𝚣"),
        },
    ),
    (
        "A",
        MathAlphanumRow {
            bold: Some("𝐀"),
            italic: Some("𝐴"),
            bold_italic: Some("𝑨"),
            script: Some("𝒜"),
            bold_script: Some("𝓐"),
            fraktur: Some("𝔄"),
            bold_fraktur: Some("𝕬"),
            double_struck: Some("𝔸"),
            sans: Some("𝖠"),
            bold_sans: Some("𝗔"),
            italic_sans: Some("𝘈"),
            bold_italic_sans: Some("𝘼"),
            monospace: Some("𝙰"),
        },
    ),
    (
        "B",
        MathAlphanumRow {
            bold: Some("𝐁"),
            italic: Some("𝐵"),
            bold_italic: Some("𝑩"),
            script: Some("ℬ"),
            bold_script: Some("𝓑"),
            fraktur: Some("𝔅"),
            bold_fraktur: Some("𝕭"),
            double_struck: Some("𝔹"),
            sans: Some("𝖡"),
            bold_sans: Some("𝗕"),
            italic_sans: Some("𝘉"),
            bold_italic_sans: Some("𝘽"),
            monospace: Some("𝙱"),
        },
    ),
    (
        "C",
        MathAlphanumRow {
            bold: Some("𝐂"),
            italic: Some("𝐶"),
            bold_italic: Some("𝑪"),
            script: Some("𝒞"),
            bold_script: Some("𝓒"),
            fraktur: Some("ℭ"),
            bold_fraktur: Some("𝕮"),
            double_struck: Some("ℂ"),
            sans: Some("𝖢"),
            bold_sans: Some("𝗖"),
            italic_sans: Some("𝘊"),
            bold_italic_sans: Some("𝘾"),
            monospace: Some("𝙲"),
        },
    ),
    (
        "D",
        MathAlphanumRow {
            bold: Some("𝐃"),
            italic: Some("𝐷"),
            bold_italic: Some("𝑫"),
            script: Some("𝒟"),
            bold_script: Some("𝓓"),
            fraktur: Some("𝔇"),
            bold_fraktur: Some("𝕯"),
            double_struck: Some("𝔻"),
            sans: Some("𝖣"),
            bold_sans: Some("𝗗"),
            italic_sans: Some("𝘋"),
            bold_italic_sans: Some("𝘿"),
            monospace: Some("𝙳"),
        },
    ),
    (
        "E",
        MathAlphanumRow {
            bold: Some("𝐄"),
            italic: Some("𝐸"),
            bold_italic: Some("𝑬"),
            script: Some("ℰ"),
            bold_script: Some("𝓔"),
            fraktur: Some("𝔈"),
            bold_fraktur: Some("𝕰"),
            double_struck: Some("𝔼"),
            sans: Some("𝖤"),
            bold_sans: Some("𝗘"),
            italic_sans: Some("𝘌"),
            bold_italic_sans: Some("𝙀"),
            monospace: Some("𝙴"),
        },
    ),
    (
        "F",
        MathAlphanumRow {
            bold: Some("𝐅"),
            italic: Some("𝐹"),
            bold_italic: Some("𝑭"),
            script: Some("ℱ"),
            bold_script: Some("𝓕"),
            fraktur: Some("𝔉"),
            bold_fraktur: Some("𝕱"),
            double_struck: Some("𝔽"),
            sans: Some("𝖥"),
            bold_sans: Some("𝗙"),
            italic_sans: Some("𝘍"),
            bold_italic_sans: Some("𝙁"),
            monospace: Some("𝙵"),
        },
    ),
    (
        "G",
        MathAlphanumRow {
            bold: Some("𝐆"),
            italic: Some("𝐺"),
            bold_italic: Some("𝑮"),
            script: Some("𝒢"),
            bold_script: Some("𝓖"),
            fraktur: Some("𝔊"),
            bold_fraktur: Some("𝕲"),
            double_struck: Some("𝔾"),
            sans: Some("𝖦"),
            bold_sans: Some("𝗚"),
            italic_sans: Some("𝘎"),
            bold_italic_sans: Some("𝙂"),
            monospace: Some("𝙶"),
        },
    ),
    (
        "H",
        MathAlphanumRow {
            bold: Some("𝐇"),
            italic: Some("𝐻"),
            bold_italic: Some("𝑯"),
            script: Some("ℋ"),
            bold_script: Some("𝓗"),
            fraktur: Some("ℌ"),
            bold_fraktur: Some("𝕳"),
            double_struck: Some("ℍ"),
            sans: Some("𝖧"),
            bold_sans: Some("𝗛"),
            italic_sans: Some("𝘏"),
            bold_italic_sans: Some("𝙃"),
            monospace: Some("𝙷"),
        },
    ),
    (
        "I",
        MathAlphanumRow {
            bold: Some("𝐈"),
            italic: Some("𝐼"),
            bold_italic: Some("𝑰"),
            script: Some("ℐ"),
            bold_script: Some("𝓘"),
            fraktur: Some("ℑ"),
            bold_fraktur: Some("𝕴"),
            double_struck: Some("𝕀"),
            sans: Some("𝖨"),
            bold_sans: Some("𝗜"),
            italic_sans: Some("𝘐"),
            bold_italic_sans: Some("𝙄"),
            monospace: Some("𝙸"),
        },
    ),
    (
        "J",
        MathAlphanumRow {
            bold: Some("𝐉"),
            italic: Some("𝐽"),
            bold_italic: Some("𝑱"),
            script: Some("𝒥"),
            bold_script: Some("𝓙"),
            fraktur: Some("𝔍"),
            bold_fraktur: Some("𝕵"),
            double_struck: Some("𝕁"),
            sans: Some("𝖩"),
            bold_sans: Some("𝗝"),
            italic_sans: Some("𝘑"),
            bold_italic_sans: Some("𝙅"),
            monospace: Some("𝙹"),
        },
    ),
    (
        "K",
        MathAlphanumRow {
            bold: Some("𝐊"),
            italic: Some("𝐾"),
            bold_italic: Some("𝑲"),
            script: Some("𝒦"),
            bold_script: Some("𝓚"),
            fraktur: Some("𝔎"),
            bold_fraktur: Some("𝕶"),
            double_struck: Some("𝕂"),
            sans: Some("𝖪"),
            bold_sans: Some("𝗞"),
            italic_sans: Some("𝘒"),
            bold_italic_sans: Some("𝙆"),
            monospace: Some("𝙺"),
        },
    ),
    (
        "L",
        MathAlphanumRow {
            bold: Some("𝐋"),
            italic: Some("𝐿"),
            bold_italic: Some("𝑳"),
            script: Some("ℒ"),
            bold_script: Some("𝓛"),
            fraktur: Some("𝔏"),
            bold_fraktur: Some("𝕷"),
            double_struck: Some("𝕃"),
            sans: Some("𝖫"),
            bold_sans: Some("𝗟"),
            italic_sans: Some("𝘓"),
            bold_italic_sans: Some("𝙇"),
            monospace: Some("𝙻"),
        },
    ),
    (
        "M",
        MathAlphanumRow {
            bold: Some("𝐌"),
            italic: Some("𝑀"),
            bold_italic: Some("𝑴"),
            script: Some("ℳ"),
            bold_script: Some("𝓜"),
            fraktur: Some("𝔐"),
            bold_fraktur: Some("𝕸"),
            double_struck: Some("𝕄"),
            sans: Some("𝖬"),
            bold_sans: Some("𝗠"),
            italic_sans: Some("𝘔"),
            bold_italic_sans: Some("𝙈"),
            monospace: Some("𝙼"),
        },
    ),
    (
        "N",
        MathAlphanumRow {
            bold: Some("𝐍"),
            italic: Some("𝑁"),
            bold_italic: Some("𝑵"),
            script: Some("𝒩"),
            bold_script: Some("𝓝"),
            fraktur: Some("𝔑"),
            bold_fraktur: Some("𝕹"),
            double_struck: Some("ℕ"),
            sans: Some("𝖭"),
            bold_sans: Some("𝗡"),
            italic_sans: Some("𝘕"),
            bold_italic_sans: Some("𝙉"),
            monospace: Some("𝙽"),
        },
    ),
    (
        "O",
        MathAlphanumRow {
            bold: Some("𝐎"),
            italic: Some("𝑂"),
            bold_italic: Some("𝑶"),
            script: Some("𝒪"),
            bold_script: Some("𝓞"),
            fraktur: Some("𝔒"),
            bold_fraktur: Some("𝕺"),
            double_struck: Some("𝕆"),
            sans: Some("𝖮"),
            bold_sans: Some("𝗢"),
            italic_sans: Some("𝘖"),
            bold_italic_sans: Some("𝙊"),
            monospace: Some("𝙾"),
        },
    ),
    (
        "P",
        MathAlphanumRow {
            bold: Some("𝐏"),
            italic: Some("𝑃"),
            bold_italic: Some("𝑷"),
            script: Some("𝒫"),
            bold_script: Some("𝓟"),
            fraktur: Some("𝔓"),
            bold_fraktur: Some("𝕻"),
            double_struck: Some("ℙ"),
            sans: Some("𝖯"),
            bold_sans: Some("𝗣"),
            italic_sans: Some("𝘗"),
            bold_italic_sans: Some("𝙋"),
            monospace: Some("𝙿"),
        },
    ),
    (
        "Q",
        MathAlphanumRow {
            bold: Some("𝐐"),
            italic: Some("𝑄"),
            bold_italic: Some("𝑸"),
            script: Some("𝒬"),
            bold_script: Some("𝓠"),
            fraktur: Some("𝔔"),
            bold_fraktur: Some("𝕼"),
            double_struck: Some("ℚ"),
            sans: Some("𝖰"),
            bold_sans: Some("𝗤"),
            italic_sans: Some("𝘘"),
            bold_italic_sans: Some("𝙌"),
            monospace: Some("𝚀"),
        },
    ),
    (
        "R",
        MathAlphanumRow {
            bold: Some("𝐑"),
            italic: Some("𝑅"),
            bold_italic: Some("𝑹"),
            script: Some("ℛ"),
            bold_script: Some("𝓡"),
            fraktur: Some("ℜ"),
            bold_fraktur: Some("𝕽"),
            double_struck: Some("ℝ"),
            sans: Some("𝖱"),
            bold_sans: Some("𝗥"),
            italic_sans: Some("𝘙"),
            bold_italic_sans: Some("𝙍"),
            monospace: Some("𝚁"),
        },
    ),
    (
        "S",
        MathAlphanumRow {
            bold: Some("𝐒"),
            italic: Some("𝑆"),
            bold_italic: Some("𝑺"),
            script: Some("𝒮"),
            bold_script: Some("𝓢"),
            fraktur: Some("𝔖"),
            bold_fraktur: Some("𝕾"),
            double_struck: Some("𝕊"),
            sans: Some("𝖲"),
            bold_sans: Some("𝗦"),
            italic_sans: Some("𝘚"),
            bold_italic_sans: Some("𝙎"),
            monospace: Some("𝚂"),
        },
    ),
    (
        "T",
        MathAlphanumRow {
            bold: Some("𝐓"),
            italic: Some("𝑇"),
            bold_italic: Some("𝑻"),
            script: Some("𝒯"),
            bold_script: Some("𝓣"),
            fraktur: Some("𝔗"),
            bold_fraktur: Some("𝕿"),
            double_struck: Some("𝕋"),
            sans: Some("𝖳"),
            bold_sans: Some("𝗧"),
            italic_sans: Some("𝘛"),
            bold_italic_sans: Some("𝙏"),
            monospace: Some("𝚃"),
        },
    ),
    (
        "U",
        MathAlphanumRow {
            bold: Some("𝐔"),
            italic: Some("𝑈"),
            bold_italic: Some("𝑼"),
            script: Some("𝒰"),
            bold_script: Some("𝓤"),
            fraktur: Some("𝔘"),
            bold_fraktur: Some("𝖀"),
            double_struck: Some("𝕌"),
            sans: Some("𝖴"),
            bold_sans: Some("𝗨"),
            italic_sans: Some("𝘜"),
            bold_italic_sans: Some("𝙐"),
            monospace: Some("𝚄"),
        },
    ),
    (
        "V",
        MathAlphanumRow {
            bold: Some("𝐕"),
            italic: Some("𝑉"),
            bold_italic: Some("𝑽"),
            script: Some("𝒱"),
            bold_script: Some("𝓥"),
            fraktur: Some("𝔙"),
            bold_fraktur: Some("𝖁"),
            double_struck: Some("𝕍"),
            sans: Some("𝖵"),
            bold_sans: Some("𝗩"),
            italic_sans: Some("𝘝"),
            bold_italic_sans: Some("𝙑"),
            monospace: Some("𝚅"),
        },
    ),
    (
        "W",
        MathAlphanumRow {
            bold: Some("𝐖"),
            italic: Some("𝑊"),
            bold_italic: Some("𝑾"),
            script: Some("𝒲"),
            bold_script: Some("𝓦"),
            fraktur: Some("𝔚"),
            bold_fraktur: Some("𝖂"),
            double_struck: Some("𝕎"),
            sans: Some("𝖶"),
            bold_sans: Some("𝗪"),
            italic_sans: Some("𝘞"),
            bold_italic_sans: Some("𝙒"),
            monospace: Some("𝚆"),
        },
    ),
    (
        "X",
        MathAlphanumRow {
            bold: Some("𝐗"),
            italic: Some("𝑋"),
            bold_italic: Some("𝑿"),
            script: Some("𝒳"),
            bold_script: Some("𝓧"),
            fraktur: Some("𝔛"),
            bold_fraktur: Some("𝖃"),
            double_struck: Some("𝕏"),
            sans: Some("𝖷"),
            bold_sans: Some("𝗫"),
            italic_sans: Some("𝘟"),
            bold_italic_sans: Some("𝙓"),
            monospace: Some("𝚇"),
        },
    ),
    (
        "Y",
        MathAlphanumRow {
            bold: Some("𝐘"),
            italic: Some("𝑌"),
            bold_italic: Some("𝒀"),
            script: Some("𝒴"),
            bold_script: Some("𝓨"),
            fraktur: Some("𝔜"),
            bold_fraktur: Some("𝖄"),
            double_struck: Some("𝕐"),
            sans: Some("𝖸"),
            bold_sans: Some("𝗬"),
            italic_sans: Some("𝘠"),
            bold_italic_sans: Some("𝙔"),
            monospace: Some("𝚈"),
        },
    ),
    (
        "Z",
        MathAlphanumRow {
            bold: Some("𝐙"),
            italic: Some("𝑍"),
            bold_italic: Some("𝒁"),
            script: Some("𝒵"),
            bold_script: Some("𝓩"),
            fraktur: Some("ℨ"),
            bold_fraktur: Some("𝖅"),
            double_struck: Some("ℤ"),
            sans: Some("𝖹"),
            bold_sans: Some("𝗭"),
            italic_sans: Some("𝘡"),
            bold_italic_sans: Some("𝙕"),
            monospace: Some("𝚉"),
        },
    ),
    (
        "α",
        MathAlphanumRow {
            bold: Some("𝛂"),
            italic: Some("𝛼"),
            bold_italic: Some("𝜶"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝰"),
            italic_sans: None,
            bold_italic_sans: Some("𝞪"),
            monospace: None,
        },
    ),
    (
        "β",
        MathAlphanumRow {
            bold: Some("𝛃"),
            italic: Some("𝛽"),
            bold_italic: Some("𝜷"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝱"),
            italic_sans: None,
            bold_italic_sans: Some("𝞫"),
            monospace: None,
        },
    ),
    (
        "γ",
        MathAlphanumRow {
            bold: Some("𝛄"),
            italic: Some("𝛾"),
            bold_italic: Some("𝜸"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝲"),
            italic_sans: None,
            bold_italic_sans: Some("𝞬"),
            monospace: None,
        },
    ),
    (
        "δ",
        MathAlphanumRow {
            bold: Some("𝛅"),
            italic: Some("𝛿"),
            bold_italic: Some("𝜹"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝳"),
            italic_sans: None,
            bold_italic_sans: Some("𝞭"),
            monospace: None,
        },
    ),
    (
        "ε",
        MathAlphanumRow {
            bold: Some("𝛆"),
            italic: Some("𝜀"),
            bold_italic: Some("𝜺"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝴"),
            italic_sans: None,
            bold_italic_sans: Some("𝞮"),
            monospace: None,
        },
    ),
    (
        "ζ",
        MathAlphanumRow {
            bold: Some("𝛇"),
            italic: Some("𝜁"),
            bold_italic: Some("𝜻"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝵"),
            italic_sans: None,
            bold_italic_sans: Some("𝞯"),
            monospace: None,
        },
    ),
    (
        "η",
        MathAlphanumRow {
            bold: Some("𝛈"),
            italic: Some("𝜂"),
            bold_italic: Some("𝜼"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝶"),
            italic_sans: None,
            bold_italic_sans: Some("𝞰"),
            monospace: None,
        },
    ),
    (
        "θ",
        MathAlphanumRow {
            bold: Some("𝛉"),
            italic: Some("𝜃"),
            bold_italic: Some("𝜽"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝷"),
            italic_sans: None,
            bold_italic_sans: Some("𝞱"),
            monospace: None,
        },
    ),
    (
        "ι",
        MathAlphanumRow {
            bold: Some("𝛊"),
            italic: Some("𝜄"),
            bold_italic: Some("𝜾"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝸"),
            italic_sans: None,
            bold_italic_sans: Some("𝞲"),
            monospace: None,
        },
    ),
    (
        "κ",
        MathAlphanumRow {
            bold: Some("𝛋"),
            italic: Some("𝜅"),
            bold_italic: Some("𝜿"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝹"),
            italic_sans: None,
            bold_italic_sans: Some("𝞳"),
            monospace: None,
        },
    ),
    (
        "λ",
        MathAlphanumRow {
            bold: Some("𝛌"),
            italic: Some("𝜆"),
            bold_italic: Some("𝝀"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝺"),
            italic_sans: None,
            bold_italic_sans: Some("𝞴"),
            monospace: None,
        },
    ),
    (
        "μ",
        MathAlphanumRow {
            bold: Some("𝛍"),
            italic: Some("𝜇"),
            bold_italic: Some("𝝁"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝻"),
            italic_sans: None,
            bold_italic_sans: Some("𝞵"),
            monospace: None,
        },
    ),
    (
        "ν",
        MathAlphanumRow {
            bold: Some("𝛎"),
            italic: Some("𝜈"),
            bold_italic: Some("𝝂"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝼"),
            italic_sans: None,
            bold_italic_sans: Some("𝞶"),
            monospace: None,
        },
    ),
    (
        "ξ",
        MathAlphanumRow {
            bold: Some("𝛏"),
            italic: Some("𝜉"),
            bold_italic: Some("𝝃"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝽"),
            italic_sans: None,
            bold_italic_sans: Some("𝞷"),
            monospace: None,
        },
    ),
    (
        "ο",
        MathAlphanumRow {
            bold: Some("𝛐"),
            italic: Some("𝜊"),
            bold_italic: Some("𝝄"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝾"),
            italic_sans: None,
            bold_italic_sans: Some("𝞸"),
            monospace: None,
        },
    ),
    (
        "π",
        MathAlphanumRow {
            bold: Some("𝛑"),
            italic: Some("𝜋"),
            bold_italic: Some("𝝅"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝿"),
            italic_sans: None,
            bold_italic_sans: Some("𝞹"),
            monospace: None,
        },
    ),
    (
        "ρ",
        MathAlphanumRow {
            bold: Some("𝛒"),
            italic: Some("𝜌"),
            bold_italic: Some("𝝆"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞀"),
            italic_sans: None,
            bold_italic_sans: Some("𝞺"),
            monospace: None,
        },
    ),
    (
        "ς",
        MathAlphanumRow {
            bold: Some("𝛓"),
            italic: Some("𝜍"),
            bold_italic: Some("𝝇"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞁"),
            italic_sans: None,
            bold_italic_sans: Some("𝞻"),
            monospace: None,
        },
    ),
    (
        "σ",
        MathAlphanumRow {
            bold: Some("𝛔"),
            italic: Some("𝜎"),
            bold_italic: Some("𝝈"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞂"),
            italic_sans: None,
            bold_italic_sans: Some("𝞼"),
            monospace: None,
        },
    ),
    (
        "τ",
        MathAlphanumRow {
            bold: Some("𝛕"),
            italic: Some("𝜏"),
            bold_italic: Some("𝝉"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞃"),
            italic_sans: None,
            bold_italic_sans: Some("𝞽"),
            monospace: None,
        },
    ),
    (
        "υ",
        MathAlphanumRow {
            bold: Some("𝛖"),
            italic: Some("𝜐"),
            bold_italic: Some("𝝊"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞄"),
            italic_sans: None,
            bold_italic_sans: Some("𝞾"),
            monospace: None,
        },
    ),
    (
        "φ",
        MathAlphanumRow {
            bold: Some("𝛗"),
            italic: Some("𝜑"),
            bold_italic: Some("𝝋"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞅"),
            italic_sans: None,
            bold_italic_sans: Some("𝞿"),
            monospace: None,
        },
    ),
    (
        "χ",
        MathAlphanumRow {
            bold: Some("𝛘"),
            italic: Some("𝜒"),
            bold_italic: Some("𝝌"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞆"),
            italic_sans: None,
            bold_italic_sans: Some("𝟀"),
            monospace: None,
        },
    ),
    (
        "ψ",
        MathAlphanumRow {
            bold: Some("𝛙"),
            italic: Some("𝜓"),
            bold_italic: Some("𝝍"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞇"),
            italic_sans: None,
            bold_italic_sans: Some("𝟁"),
            monospace: None,
        },
    ),
    (
        "ω",
        MathAlphanumRow {
            bold: Some("𝛚"),
            italic: Some("𝜔"),
            bold_italic: Some("𝝎"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝞈"),
            italic_sans: None,
            bold_italic_sans: Some("𝟂"),
            monospace: None,
        },
    ),
    (
        "Α",
        MathAlphanumRow {
            bold: Some("𝚨"),
            italic: Some("𝛢"),
            bold_italic: Some("𝜜"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝖"),
            italic_sans: None,
            bold_italic_sans: Some("𝞐"),
            monospace: None,
        },
    ),
    (
        "Β",
        MathAlphanumRow {
            bold: Some("𝚩"),
            italic: Some("𝛣"),
            bold_italic: Some("𝜝"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝗"),
            italic_sans: None,
            bold_italic_sans: Some("𝞑"),
            monospace: None,
        },
    ),
    (
        "Γ",
        MathAlphanumRow {
            bold: Some("𝚪"),
            italic: Some("𝛤"),
            bold_italic: Some("𝜞"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝘"),
            italic_sans: None,
            bold_italic_sans: Some("𝞒"),
            monospace: None,
        },
    ),
    (
        "Δ",
        MathAlphanumRow {
            bold: Some("𝚫"),
            italic: Some("𝛥"),
            bold_italic: Some("𝜟"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝙"),
            italic_sans: None,
            bold_italic_sans: Some("𝞓"),
            monospace: None,
        },
    ),
    (
        "Ε",
        MathAlphanumRow {
            bold: Some("𝚬"),
            italic: Some("𝛦"),
            bold_italic: Some("𝜠"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝚"),
            italic_sans: None,
            bold_italic_sans: Some("𝞔"),
            monospace: None,
        },
    ),
    (
        "Ζ",
        MathAlphanumRow {
            bold: Some("𝚭"),
            italic: Some("𝛧"),
            bold_italic: Some("𝜡"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝛"),
            italic_sans: None,
            bold_italic_sans: Some("𝞕"),
            monospace: None,
        },
    ),
    (
        "Η",
        MathAlphanumRow {
            bold: Some("𝚮"),
            italic: Some("𝛨"),
            bold_italic: Some("𝜢"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝜"),
            italic_sans: None,
            bold_italic_sans: Some("𝞖"),
            monospace: None,
        },
    ),
    (
        "Θ",
        MathAlphanumRow {
            bold: Some("𝚯"),
            italic: Some("𝛩"),
            bold_italic: Some("𝜣"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝝"),
            italic_sans: None,
            bold_italic_sans: Some("𝞗"),
            monospace: None,
        },
    ),
    (
        "Ι",
        MathAlphanumRow {
            bold: Some("𝚰"),
            italic: Some("𝛪"),
            bold_italic: Some("𝜤"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝞"),
            italic_sans: None,
            bold_italic_sans: Some("𝞘"),
            monospace: None,
        },
    ),
    (
        "Κ",
        MathAlphanumRow {
            bold: Some("𝚱"),
            italic: Some("𝛫"),
            bold_italic: Some("𝜥"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝟"),
            italic_sans: None,
            bold_italic_sans: Some("𝞙"),
            monospace: None,
        },
    ),
    (
        "Λ",
        MathAlphanumRow {
            bold: Some("𝚲"),
            italic: Some("𝛬"),
            bold_italic: Some("𝜦"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝠"),
            italic_sans: None,
            bold_italic_sans: Some("𝞚"),
            monospace: None,
        },
    ),
    (
        "Μ",
        MathAlphanumRow {
            bold: Some("𝚳"),
            italic: Some("𝛭"),
            bold_italic: Some("𝜧"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝡"),
            italic_sans: None,
            bold_italic_sans: Some("𝞛"),
            monospace: None,
        },
    ),
    (
        "Ν",
        MathAlphanumRow {
            bold: Some("𝚴"),
            italic: Some("𝛮"),
            bold_italic: Some("𝜨"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝢"),
            italic_sans: None,
            bold_italic_sans: Some("𝞜"),
            monospace: None,
        },
    ),
    (
        "Ξ",
        MathAlphanumRow {
            bold: Some("𝚵"),
            italic: Some("𝛯"),
            bold_italic: Some("𝜩"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝣"),
            italic_sans: None,
            bold_italic_sans: Some("𝞝"),
            monospace: None,
        },
    ),
    (
        "Ο",
        MathAlphanumRow {
            bold: Some("𝚶"),
            italic: Some("𝛰"),
            bold_italic: Some("𝜪"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝤"),
            italic_sans: None,
            bold_italic_sans: Some("𝞞"),
            monospace: None,
        },
    ),
    (
        "Π",
        MathAlphanumRow {
            bold: Some("𝚷"),
            italic: Some("𝛱"),
            bold_italic: Some("𝜫"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝥"),
            italic_sans: None,
            bold_italic_sans: Some("𝞟"),
            monospace: None,
        },
    ),
    (
        "Ρ",
        MathAlphanumRow {
            bold: Some("𝚸"),
            italic: Some("𝛲"),
            bold_italic: Some("𝜬"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝦"),
            italic_sans: None,
            bold_italic_sans: Some("𝞠"),
            monospace: None,
        },
    ),
    (
        "Σ",
        MathAlphanumRow {
            bold: Some("𝚺"),
            italic: Some("𝛴"),
            bold_italic: Some("𝜮"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝨"),
            italic_sans: None,
            bold_italic_sans: Some("𝞢"),
            monospace: None,
        },
    ),
    (
        "Τ",
        MathAlphanumRow {
            bold: Some("𝚻"),
            italic: Some("𝛵"),
            bold_italic: Some("𝜯"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝩"),
            italic_sans: None,
            bold_italic_sans: Some("𝞣"),
            monospace: None,
        },
    ),
    (
        "Υ",
        MathAlphanumRow {
            bold: Some("𝚼"),
            italic: Some("𝛶"),
            bold_italic: Some("𝜰"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝪"),
            italic_sans: None,
            bold_italic_sans: Some("𝞤"),
            monospace: None,
        },
    ),
    (
        "Φ",
        MathAlphanumRow {
            bold: Some("𝚽"),
            italic: Some("𝛷"),
            bold_italic: Some("𝜱"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝫"),
            italic_sans: None,
            bold_italic_sans: Some("𝞥"),
            monospace: None,
        },
    ),
    (
        "Χ",
        MathAlphanumRow {
            bold: Some("𝚾"),
            italic: Some("𝛸"),
            bold_italic: Some("𝜲"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝬"),
            italic_sans: None,
            bold_italic_sans: Some("𝞦"),
            monospace: None,
        },
    ),
    (
        "Ψ",
        MathAlphanumRow {
            bold: Some("𝚿"),
            italic: Some("𝛹"),
            bold_italic: Some("𝜳"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝭"),
            italic_sans: None,
            bold_italic_sans: Some("𝞧"),
            monospace: None,
        },
    ),
    (
        "Ω",
        MathAlphanumRow {
            bold: Some("𝛀"),
            italic: Some("𝛺"),
            bold_italic: Some("𝜴"),
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: None,
            sans: None,
            bold_sans: Some("𝝮"),
            italic_sans: None,
            bold_italic_sans: Some("𝞨"),
            monospace: None,
        },
    ),
    (
        "0",
        MathAlphanumRow {
            bold: Some("𝟎"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟘"),
            sans: None,
            bold_sans: Some("𝟢"),
            italic_sans: Some("𝟬"),
            bold_italic_sans: None,
            monospace: Some("𝟶"),
        },
    ),
    (
        "1",
        MathAlphanumRow {
            bold: Some("𝟏"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟙"),
            sans: None,
            bold_sans: Some("𝟣"),
            italic_sans: Some("𝟭"),
            bold_italic_sans: None,
            monospace: Some("𝟷"),
        },
    ),
    (
        "2",
        MathAlphanumRow {
            bold: Some("𝟐"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟚"),
            sans: None,
            bold_sans: Some("𝟤"),
            italic_sans: Some("𝟮"),
            bold_italic_sans: None,
            monospace: Some("𝟸"),
        },
    ),
    (
        "3",
        MathAlphanumRow {
            bold: Some("𝟑"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟛"),
            sans: None,
            bold_sans: Some("𝟥"),
            italic_sans: Some("𝟯"),
            bold_italic_sans: None,
            monospace: Some("𝟹"),
        },
    ),
    (
        "4",
        MathAlphanumRow {
            bold: Some("𝟒"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟜"),
            sans: None,
            bold_sans: Some("𝟦"),
            italic_sans: Some("𝟰"),
            bold_italic_sans: None,
            monospace: Some("𝟺"),
        },
    ),
    (
        "5",
        MathAlphanumRow {
            bold: Some("𝟓"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟝"),
            sans: None,
            bold_sans: Some("𝟧"),
            italic_sans: Some("𝟱"),
            bold_italic_sans: None,
            monospace: Some("𝟻"),
        },
    ),
    (
        "6",
        MathAlphanumRow {
            bold: Some("𝟔"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟞"),
            sans: None,
            bold_sans: Some("𝟨"),
            italic_sans: Some("𝟲"),
            bold_italic_sans: None,
            monospace: Some("𝟼"),
        },
    ),
    (
        "7",
        MathAlphanumRow {
            bold: Some("𝟕"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟟"),
            sans: None,
            bold_sans: Some("𝟩"),
            italic_sans: Some("𝟳"),
            bold_italic_sans: None,
            monospace: Some("𝟽"),
        },
    ),
    (
        "8",
        MathAlphanumRow {
            bold: Some("𝟖"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟠"),
            sans: None,
            bold_sans: Some("𝟪"),
            italic_sans: Some("𝟴"),
            bold_italic_sans: None,
            monospace: Some("𝟾"),
        },
    ),
    (
        "9",
        MathAlphanumRow {
            bold: Some("𝟗"),
            italic: None,
            bold_italic: None,
            script: None,
            bold_script: None,
            fraktur: None,
            bold_fraktur: None,
            double_struck: Some("𝟡"),
            sans: None,
            bold_sans: Some("𝟫"),
            italic_sans: Some("𝟵"),
            bold_italic_sans: None,
            monospace: Some("𝟿"),
        },
    ),
];

pub fn math_alphanum(ch: &str) -> Option<&'static MathAlphanumRow> {
    MATH_ALPHANUM.iter().find(|(k, _)| *k == ch).map(|(_, r)| r)
}

impl MathAlphanumRow {
    pub fn get(&self, variant: MathAlphanumVariant) -> Option<&'static str> {
        match variant {
            MathAlphanumVariant::Bold => self.bold,
            MathAlphanumVariant::Italic => self.italic,
            MathAlphanumVariant::BoldItalic => self.bold_italic,
            MathAlphanumVariant::Script => self.script,
            MathAlphanumVariant::BoldScript => self.bold_script,
            MathAlphanumVariant::Fraktur => self.fraktur,
            MathAlphanumVariant::BoldFraktur => self.bold_fraktur,
            MathAlphanumVariant::DoubleStruck => self.double_struck,
            MathAlphanumVariant::Sans => self.sans,
            MathAlphanumVariant::BoldSans => self.bold_sans,
            MathAlphanumVariant::ItalicSans => self.italic_sans,
            MathAlphanumVariant::BoldItalicSans => self.bold_italic_sans,
            MathAlphanumVariant::Monospace => self.monospace,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_has_latin_and_sample_glyph() {
        let a = math_alphanum("a").expect("a");
        assert_eq!(a.bold, Some("𝐚"));
        assert!(math_alphanum("α").is_some() || math_alphanum("A").is_some());
        assert_eq!(MATH_ALPHANUM.len(), 111);
    }
}
