/** Mathematical alphanumeric variants from LyX 2.5 `unicode_alphanum_variants` (DL153). */
export type MathAlphanumVariant =
  | "bold"
  | "italic"
  | "boldItalic"
  | "script"
  | "boldScript"
  | "fraktur"
  | "boldFraktur"
  | "doubleStruck"
  | "sans"
  | "boldSans"
  | "italicSans"
  | "boldItalicSans"
  | "monospace";

export type MathAlphanumRow = Partial<Record<MathAlphanumVariant, string>>;

export const MATH_ALPHANUM: Record<string, MathAlphanumRow> = {
  "a": { bold: "𝐚", italic: "𝑎", boldItalic: "𝒂", script: "𝒶", boldScript: "𝓪", fraktur: "𝔞", boldFraktur: "𝖆", doubleStruck: "𝕒", sans: "𝖺", boldSans: "𝗮", italicSans: "𝘢", boldItalicSans: "𝙖", monospace: "𝚊" },
  "b": { bold: "𝐛", italic: "𝑏", boldItalic: "𝒃", script: "𝒷", boldScript: "𝓫", fraktur: "𝔟", boldFraktur: "𝖇", doubleStruck: "𝕓", sans: "𝖻", boldSans: "𝗯", italicSans: "𝘣", boldItalicSans: "𝙗", monospace: "𝚋" },
  "c": { bold: "𝐜", italic: "𝑐", boldItalic: "𝒄", script: "𝒸", boldScript: "𝓬", fraktur: "𝔠", boldFraktur: "𝖈", doubleStruck: "𝕔", sans: "𝖼", boldSans: "𝗰", italicSans: "𝘤", boldItalicSans: "𝙘", monospace: "𝚌" },
  "d": { bold: "𝐝", italic: "𝑑", boldItalic: "𝒅", script: "𝒹", boldScript: "𝓭", fraktur: "𝔡", boldFraktur: "𝖉", doubleStruck: "𝕕", sans: "𝖽", boldSans: "𝗱", italicSans: "𝘥", boldItalicSans: "𝙙", monospace: "𝚍" },
  "e": { bold: "𝐞", italic: "𝑒", boldItalic: "𝒆", script: "ℯ", boldScript: "𝓮", fraktur: "𝔢", boldFraktur: "𝖊", doubleStruck: "𝕖", sans: "𝖾", boldSans: "𝗲", italicSans: "𝘦", boldItalicSans: "𝙚", monospace: "𝚎" },
  "f": { bold: "𝐟", italic: "𝑓", boldItalic: "𝒇", script: "𝒻", boldScript: "𝓯", fraktur: "𝔣", boldFraktur: "𝖋", doubleStruck: "𝕗", sans: "𝖿", boldSans: "𝗳", italicSans: "𝘧", boldItalicSans: "𝙛", monospace: "𝚏" },
  "g": { bold: "𝐠", italic: "𝑔", boldItalic: "𝒈", script: "ℊ", boldScript: "𝓰", fraktur: "𝔤", boldFraktur: "𝖌", doubleStruck: "𝕘", sans: "𝗀", boldSans: "𝗴", italicSans: "𝘨", boldItalicSans: "𝙜", monospace: "𝚐" },
  "h": { bold: "𝐡", italic: "ℎ", boldItalic: "𝒉", script: "𝒽", boldScript: "𝓱", fraktur: "𝔥", boldFraktur: "𝖍", doubleStruck: "𝕙", sans: "𝗁", boldSans: "𝗵", italicSans: "𝘩", boldItalicSans: "𝙝", monospace: "𝚑" },
  "i": { bold: "𝐢", italic: "𝑖", boldItalic: "𝒊", script: "𝒾", boldScript: "𝓲", fraktur: "𝔦", boldFraktur: "𝖎", doubleStruck: "𝕚", sans: "𝗂", boldSans: "𝗶", italicSans: "𝘪", boldItalicSans: "𝙞", monospace: "𝚒" },
  "j": { bold: "𝐣", italic: "𝑗", boldItalic: "𝒋", script: "𝒿", boldScript: "𝓳", fraktur: "𝔧", boldFraktur: "𝖏", doubleStruck: "𝕛", sans: "𝗃", boldSans: "𝗷", italicSans: "𝘫", boldItalicSans: "𝙟", monospace: "𝚓" },
  "k": { bold: "𝐤", italic: "𝑘", boldItalic: "𝒌", script: "𝓀", boldScript: "𝓴", fraktur: "𝔨", boldFraktur: "𝖐", doubleStruck: "𝕜", sans: "𝗄", boldSans: "𝗸", italicSans: "𝘬", boldItalicSans: "𝙠", monospace: "𝚔" },
  "l": { bold: "𝐥", italic: "𝑙", boldItalic: "𝒍", script: "𝓁", boldScript: "𝓵", fraktur: "𝔩", boldFraktur: "𝖑", doubleStruck: "𝕝", sans: "𝗅", boldSans: "𝗹", italicSans: "𝘭", boldItalicSans: "𝙡", monospace: "𝚕" },
  "m": { bold: "𝐦", italic: "𝑚", boldItalic: "𝒎", script: "𝓂", boldScript: "𝓶", fraktur: "𝔪", boldFraktur: "𝖒", doubleStruck: "𝕞", sans: "𝗆", boldSans: "𝗺", italicSans: "𝘮", boldItalicSans: "𝙢", monospace: "𝚖" },
  "n": { bold: "𝐧", italic: "𝑛", boldItalic: "𝒏", script: "𝓃", boldScript: "𝓷", fraktur: "𝔫", boldFraktur: "𝖓", doubleStruck: "𝕟", sans: "𝗇", boldSans: "𝗻", italicSans: "𝘯", boldItalicSans: "𝙣", monospace: "𝚗" },
  "o": { bold: "𝐨", italic: "𝑜", boldItalic: "𝒐", script: "ℴ", boldScript: "𝓸", fraktur: "𝔬", boldFraktur: "𝖔", doubleStruck: "𝕠", sans: "𝗈", boldSans: "𝗼", italicSans: "𝘰", boldItalicSans: "𝙤", monospace: "𝚘" },
  "p": { bold: "𝐩", italic: "𝑝", boldItalic: "𝒑", script: "𝓅", boldScript: "𝓹", fraktur: "𝔭", boldFraktur: "𝖕", doubleStruck: "𝕡", sans: "𝗉", boldSans: "𝗽", italicSans: "𝘱", boldItalicSans: "𝙥", monospace: "𝚙" },
  "q": { bold: "𝐪", italic: "𝑞", boldItalic: "𝒒", script: "𝓆", boldScript: "𝓺", fraktur: "𝔮", boldFraktur: "𝖖", doubleStruck: "𝕢", sans: "𝗊", boldSans: "𝗾", italicSans: "𝘲", boldItalicSans: "𝙦", monospace: "𝚚" },
  "r": { bold: "𝐫", italic: "𝑟", boldItalic: "𝒓", script: "𝓇", boldScript: "𝓻", fraktur: "𝔯", boldFraktur: "𝖗", doubleStruck: "𝕣", sans: "𝗋", boldSans: "𝗿", italicSans: "𝘳", boldItalicSans: "𝙧", monospace: "𝚛" },
  "s": { bold: "𝐬", italic: "𝑠", boldItalic: "𝒔", script: "𝓈", boldScript: "𝓼", fraktur: "𝔰", boldFraktur: "𝖘", doubleStruck: "𝕤", sans: "𝗌", boldSans: "𝘀", italicSans: "𝘴", boldItalicSans: "𝙨", monospace: "𝚜" },
  "t": { bold: "𝐭", italic: "𝑡", boldItalic: "𝒕", script: "𝓉", boldScript: "𝓽", fraktur: "𝔱", boldFraktur: "𝖙", doubleStruck: "𝕥", sans: "𝗍", boldSans: "𝘁", italicSans: "𝘵", boldItalicSans: "𝙩", monospace: "𝚝" },
  "u": { bold: "𝐮", italic: "𝑢", boldItalic: "𝒖", script: "𝓊", boldScript: "𝓾", fraktur: "𝔲", boldFraktur: "𝖚", doubleStruck: "𝕦", sans: "𝗎", boldSans: "𝘂", italicSans: "𝘶", boldItalicSans: "𝙪", monospace: "𝚞" },
  "v": { bold: "𝐯", italic: "𝑣", boldItalic: "𝒗", script: "𝓋", boldScript: "𝓿", fraktur: "𝔳", boldFraktur: "𝖛", doubleStruck: "𝕧", sans: "𝗏", boldSans: "𝘃", italicSans: "𝘷", boldItalicSans: "𝙫", monospace: "𝚟" },
  "w": { bold: "𝐰", italic: "𝑤", boldItalic: "𝒘", script: "𝓌", boldScript: "𝔀", fraktur: "𝔴", boldFraktur: "𝖜", doubleStruck: "𝕨", sans: "𝗐", boldSans: "𝘄", italicSans: "𝘸", boldItalicSans: "𝙬", monospace: "𝚠" },
  "x": { bold: "𝐱", italic: "𝑥", boldItalic: "𝒙", script: "𝓍", boldScript: "𝔁", fraktur: "𝔵", boldFraktur: "𝖝", doubleStruck: "𝕩", sans: "𝗑", boldSans: "𝘅", italicSans: "𝘹", boldItalicSans: "𝙭", monospace: "𝚡" },
  "y": { bold: "𝐲", italic: "𝑦", boldItalic: "𝒚", script: "𝓎", boldScript: "𝔂", fraktur: "𝔶", boldFraktur: "𝖞", doubleStruck: "𝕪", sans: "𝗒", boldSans: "𝘆", italicSans: "𝘺", boldItalicSans: "𝙮", monospace: "𝚢" },
  "z": { bold: "𝐳", italic: "𝑧", boldItalic: "𝒛", script: "𝓏", boldScript: "𝔃", fraktur: "𝔷", boldFraktur: "𝖟", doubleStruck: "𝕫", sans: "𝗓", boldSans: "𝘇", italicSans: "𝘻", boldItalicSans: "𝙯", monospace: "𝚣" },
  "A": { bold: "𝐀", italic: "𝐴", boldItalic: "𝑨", script: "𝒜", boldScript: "𝓐", fraktur: "𝔄", boldFraktur: "𝕬", doubleStruck: "𝔸", sans: "𝖠", boldSans: "𝗔", italicSans: "𝘈", boldItalicSans: "𝘼", monospace: "𝙰" },
  "B": { bold: "𝐁", italic: "𝐵", boldItalic: "𝑩", script: "ℬ", boldScript: "𝓑", fraktur: "𝔅", boldFraktur: "𝕭", doubleStruck: "𝔹", sans: "𝖡", boldSans: "𝗕", italicSans: "𝘉", boldItalicSans: "𝘽", monospace: "𝙱" },
  "C": { bold: "𝐂", italic: "𝐶", boldItalic: "𝑪", script: "𝒞", boldScript: "𝓒", fraktur: "ℭ", boldFraktur: "𝕮", doubleStruck: "ℂ", sans: "𝖢", boldSans: "𝗖", italicSans: "𝘊", boldItalicSans: "𝘾", monospace: "𝙲" },
  "D": { bold: "𝐃", italic: "𝐷", boldItalic: "𝑫", script: "𝒟", boldScript: "𝓓", fraktur: "𝔇", boldFraktur: "𝕯", doubleStruck: "𝔻", sans: "𝖣", boldSans: "𝗗", italicSans: "𝘋", boldItalicSans: "𝘿", monospace: "𝙳" },
  "E": { bold: "𝐄", italic: "𝐸", boldItalic: "𝑬", script: "ℰ", boldScript: "𝓔", fraktur: "𝔈", boldFraktur: "𝕰", doubleStruck: "𝔼", sans: "𝖤", boldSans: "𝗘", italicSans: "𝘌", boldItalicSans: "𝙀", monospace: "𝙴" },
  "F": { bold: "𝐅", italic: "𝐹", boldItalic: "𝑭", script: "ℱ", boldScript: "𝓕", fraktur: "𝔉", boldFraktur: "𝕱", doubleStruck: "𝔽", sans: "𝖥", boldSans: "𝗙", italicSans: "𝘍", boldItalicSans: "𝙁", monospace: "𝙵" },
  "G": { bold: "𝐆", italic: "𝐺", boldItalic: "𝑮", script: "𝒢", boldScript: "𝓖", fraktur: "𝔊", boldFraktur: "𝕲", doubleStruck: "𝔾", sans: "𝖦", boldSans: "𝗚", italicSans: "𝘎", boldItalicSans: "𝙂", monospace: "𝙶" },
  "H": { bold: "𝐇", italic: "𝐻", boldItalic: "𝑯", script: "ℋ", boldScript: "𝓗", fraktur: "ℌ", boldFraktur: "𝕳", doubleStruck: "ℍ", sans: "𝖧", boldSans: "𝗛", italicSans: "𝘏", boldItalicSans: "𝙃", monospace: "𝙷" },
  "I": { bold: "𝐈", italic: "𝐼", boldItalic: "𝑰", script: "ℐ", boldScript: "𝓘", fraktur: "ℑ", boldFraktur: "𝕴", doubleStruck: "𝕀", sans: "𝖨", boldSans: "𝗜", italicSans: "𝘐", boldItalicSans: "𝙄", monospace: "𝙸" },
  "J": { bold: "𝐉", italic: "𝐽", boldItalic: "𝑱", script: "𝒥", boldScript: "𝓙", fraktur: "𝔍", boldFraktur: "𝕵", doubleStruck: "𝕁", sans: "𝖩", boldSans: "𝗝", italicSans: "𝘑", boldItalicSans: "𝙅", monospace: "𝙹" },
  "K": { bold: "𝐊", italic: "𝐾", boldItalic: "𝑲", script: "𝒦", boldScript: "𝓚", fraktur: "𝔎", boldFraktur: "𝕶", doubleStruck: "𝕂", sans: "𝖪", boldSans: "𝗞", italicSans: "𝘒", boldItalicSans: "𝙆", monospace: "𝙺" },
  "L": { bold: "𝐋", italic: "𝐿", boldItalic: "𝑳", script: "ℒ", boldScript: "𝓛", fraktur: "𝔏", boldFraktur: "𝕷", doubleStruck: "𝕃", sans: "𝖫", boldSans: "𝗟", italicSans: "𝘓", boldItalicSans: "𝙇", monospace: "𝙻" },
  "M": { bold: "𝐌", italic: "𝑀", boldItalic: "𝑴", script: "ℳ", boldScript: "𝓜", fraktur: "𝔐", boldFraktur: "𝕸", doubleStruck: "𝕄", sans: "𝖬", boldSans: "𝗠", italicSans: "𝘔", boldItalicSans: "𝙈", monospace: "𝙼" },
  "N": { bold: "𝐍", italic: "𝑁", boldItalic: "𝑵", script: "𝒩", boldScript: "𝓝", fraktur: "𝔑", boldFraktur: "𝕹", doubleStruck: "ℕ", sans: "𝖭", boldSans: "𝗡", italicSans: "𝘕", boldItalicSans: "𝙉", monospace: "𝙽" },
  "O": { bold: "𝐎", italic: "𝑂", boldItalic: "𝑶", script: "𝒪", boldScript: "𝓞", fraktur: "𝔒", boldFraktur: "𝕺", doubleStruck: "𝕆", sans: "𝖮", boldSans: "𝗢", italicSans: "𝘖", boldItalicSans: "𝙊", monospace: "𝙾" },
  "P": { bold: "𝐏", italic: "𝑃", boldItalic: "𝑷", script: "𝒫", boldScript: "𝓟", fraktur: "𝔓", boldFraktur: "𝕻", doubleStruck: "ℙ", sans: "𝖯", boldSans: "𝗣", italicSans: "𝘗", boldItalicSans: "𝙋", monospace: "𝙿" },
  "Q": { bold: "𝐐", italic: "𝑄", boldItalic: "𝑸", script: "𝒬", boldScript: "𝓠", fraktur: "𝔔", boldFraktur: "𝕼", doubleStruck: "ℚ", sans: "𝖰", boldSans: "𝗤", italicSans: "𝘘", boldItalicSans: "𝙌", monospace: "𝚀" },
  "R": { bold: "𝐑", italic: "𝑅", boldItalic: "𝑹", script: "ℛ", boldScript: "𝓡", fraktur: "ℜ", boldFraktur: "𝕽", doubleStruck: "ℝ", sans: "𝖱", boldSans: "𝗥", italicSans: "𝘙", boldItalicSans: "𝙍", monospace: "𝚁" },
  "S": { bold: "𝐒", italic: "𝑆", boldItalic: "𝑺", script: "𝒮", boldScript: "𝓢", fraktur: "𝔖", boldFraktur: "𝕾", doubleStruck: "𝕊", sans: "𝖲", boldSans: "𝗦", italicSans: "𝘚", boldItalicSans: "𝙎", monospace: "𝚂" },
  "T": { bold: "𝐓", italic: "𝑇", boldItalic: "𝑻", script: "𝒯", boldScript: "𝓣", fraktur: "𝔗", boldFraktur: "𝕿", doubleStruck: "𝕋", sans: "𝖳", boldSans: "𝗧", italicSans: "𝘛", boldItalicSans: "𝙏", monospace: "𝚃" },
  "U": { bold: "𝐔", italic: "𝑈", boldItalic: "𝑼", script: "𝒰", boldScript: "𝓤", fraktur: "𝔘", boldFraktur: "𝖀", doubleStruck: "𝕌", sans: "𝖴", boldSans: "𝗨", italicSans: "𝘜", boldItalicSans: "𝙐", monospace: "𝚄" },
  "V": { bold: "𝐕", italic: "𝑉", boldItalic: "𝑽", script: "𝒱", boldScript: "𝓥", fraktur: "𝔙", boldFraktur: "𝖁", doubleStruck: "𝕍", sans: "𝖵", boldSans: "𝗩", italicSans: "𝘝", boldItalicSans: "𝙑", monospace: "𝚅" },
  "W": { bold: "𝐖", italic: "𝑊", boldItalic: "𝑾", script: "𝒲", boldScript: "𝓦", fraktur: "𝔚", boldFraktur: "𝖂", doubleStruck: "𝕎", sans: "𝖶", boldSans: "𝗪", italicSans: "𝘞", boldItalicSans: "𝙒", monospace: "𝚆" },
  "X": { bold: "𝐗", italic: "𝑋", boldItalic: "𝑿", script: "𝒳", boldScript: "𝓧", fraktur: "𝔛", boldFraktur: "𝖃", doubleStruck: "𝕏", sans: "𝖷", boldSans: "𝗫", italicSans: "𝘟", boldItalicSans: "𝙓", monospace: "𝚇" },
  "Y": { bold: "𝐘", italic: "𝑌", boldItalic: "𝒀", script: "𝒴", boldScript: "𝓨", fraktur: "𝔜", boldFraktur: "𝖄", doubleStruck: "𝕐", sans: "𝖸", boldSans: "𝗬", italicSans: "𝘠", boldItalicSans: "𝙔", monospace: "𝚈" },
  "Z": { bold: "𝐙", italic: "𝑍", boldItalic: "𝒁", script: "𝒵", boldScript: "𝓩", fraktur: "ℨ", boldFraktur: "𝖅", doubleStruck: "ℤ", sans: "𝖹", boldSans: "𝗭", italicSans: "𝘡", boldItalicSans: "𝙕", monospace: "𝚉" },
  "α": { bold: "𝛂", italic: "𝛼", boldItalic: "𝜶", boldSans: "𝝰", boldItalicSans: "𝞪" },
  "β": { bold: "𝛃", italic: "𝛽", boldItalic: "𝜷", boldSans: "𝝱", boldItalicSans: "𝞫" },
  "γ": { bold: "𝛄", italic: "𝛾", boldItalic: "𝜸", boldSans: "𝝲", boldItalicSans: "𝞬" },
  "δ": { bold: "𝛅", italic: "𝛿", boldItalic: "𝜹", boldSans: "𝝳", boldItalicSans: "𝞭" },
  "ε": { bold: "𝛆", italic: "𝜀", boldItalic: "𝜺", boldSans: "𝝴", boldItalicSans: "𝞮" },
  "ζ": { bold: "𝛇", italic: "𝜁", boldItalic: "𝜻", boldSans: "𝝵", boldItalicSans: "𝞯" },
  "η": { bold: "𝛈", italic: "𝜂", boldItalic: "𝜼", boldSans: "𝝶", boldItalicSans: "𝞰" },
  "θ": { bold: "𝛉", italic: "𝜃", boldItalic: "𝜽", boldSans: "𝝷", boldItalicSans: "𝞱" },
  "ι": { bold: "𝛊", italic: "𝜄", boldItalic: "𝜾", boldSans: "𝝸", boldItalicSans: "𝞲" },
  "κ": { bold: "𝛋", italic: "𝜅", boldItalic: "𝜿", boldSans: "𝝹", boldItalicSans: "𝞳" },
  "λ": { bold: "𝛌", italic: "𝜆", boldItalic: "𝝀", boldSans: "𝝺", boldItalicSans: "𝞴" },
  "μ": { bold: "𝛍", italic: "𝜇", boldItalic: "𝝁", boldSans: "𝝻", boldItalicSans: "𝞵" },
  "ν": { bold: "𝛎", italic: "𝜈", boldItalic: "𝝂", boldSans: "𝝼", boldItalicSans: "𝞶" },
  "ξ": { bold: "𝛏", italic: "𝜉", boldItalic: "𝝃", boldSans: "𝝽", boldItalicSans: "𝞷" },
  "ο": { bold: "𝛐", italic: "𝜊", boldItalic: "𝝄", boldSans: "𝝾", boldItalicSans: "𝞸" },
  "π": { bold: "𝛑", italic: "𝜋", boldItalic: "𝝅", boldSans: "𝝿", boldItalicSans: "𝞹" },
  "ρ": { bold: "𝛒", italic: "𝜌", boldItalic: "𝝆", boldSans: "𝞀", boldItalicSans: "𝞺" },
  "ς": { bold: "𝛓", italic: "𝜍", boldItalic: "𝝇", boldSans: "𝞁", boldItalicSans: "𝞻" },
  "σ": { bold: "𝛔", italic: "𝜎", boldItalic: "𝝈", boldSans: "𝞂", boldItalicSans: "𝞼" },
  "τ": { bold: "𝛕", italic: "𝜏", boldItalic: "𝝉", boldSans: "𝞃", boldItalicSans: "𝞽" },
  "υ": { bold: "𝛖", italic: "𝜐", boldItalic: "𝝊", boldSans: "𝞄", boldItalicSans: "𝞾" },
  "φ": { bold: "𝛗", italic: "𝜑", boldItalic: "𝝋", boldSans: "𝞅", boldItalicSans: "𝞿" },
  "χ": { bold: "𝛘", italic: "𝜒", boldItalic: "𝝌", boldSans: "𝞆", boldItalicSans: "𝟀" },
  "ψ": { bold: "𝛙", italic: "𝜓", boldItalic: "𝝍", boldSans: "𝞇", boldItalicSans: "𝟁" },
  "ω": { bold: "𝛚", italic: "𝜔", boldItalic: "𝝎", boldSans: "𝞈", boldItalicSans: "𝟂" },
  "Α": { bold: "𝚨", italic: "𝛢", boldItalic: "𝜜", boldSans: "𝝖", boldItalicSans: "𝞐" },
  "Β": { bold: "𝚩", italic: "𝛣", boldItalic: "𝜝", boldSans: "𝝗", boldItalicSans: "𝞑" },
  "Γ": { bold: "𝚪", italic: "𝛤", boldItalic: "𝜞", boldSans: "𝝘", boldItalicSans: "𝞒" },
  "Δ": { bold: "𝚫", italic: "𝛥", boldItalic: "𝜟", boldSans: "𝝙", boldItalicSans: "𝞓" },
  "Ε": { bold: "𝚬", italic: "𝛦", boldItalic: "𝜠", boldSans: "𝝚", boldItalicSans: "𝞔" },
  "Ζ": { bold: "𝚭", italic: "𝛧", boldItalic: "𝜡", boldSans: "𝝛", boldItalicSans: "𝞕" },
  "Η": { bold: "𝚮", italic: "𝛨", boldItalic: "𝜢", boldSans: "𝝜", boldItalicSans: "𝞖" },
  "Θ": { bold: "𝚯", italic: "𝛩", boldItalic: "𝜣", boldSans: "𝝝", boldItalicSans: "𝞗" },
  "Ι": { bold: "𝚰", italic: "𝛪", boldItalic: "𝜤", boldSans: "𝝞", boldItalicSans: "𝞘" },
  "Κ": { bold: "𝚱", italic: "𝛫", boldItalic: "𝜥", boldSans: "𝝟", boldItalicSans: "𝞙" },
  "Λ": { bold: "𝚲", italic: "𝛬", boldItalic: "𝜦", boldSans: "𝝠", boldItalicSans: "𝞚" },
  "Μ": { bold: "𝚳", italic: "𝛭", boldItalic: "𝜧", boldSans: "𝝡", boldItalicSans: "𝞛" },
  "Ν": { bold: "𝚴", italic: "𝛮", boldItalic: "𝜨", boldSans: "𝝢", boldItalicSans: "𝞜" },
  "Ξ": { bold: "𝚵", italic: "𝛯", boldItalic: "𝜩", boldSans: "𝝣", boldItalicSans: "𝞝" },
  "Ο": { bold: "𝚶", italic: "𝛰", boldItalic: "𝜪", boldSans: "𝝤", boldItalicSans: "𝞞" },
  "Π": { bold: "𝚷", italic: "𝛱", boldItalic: "𝜫", boldSans: "𝝥", boldItalicSans: "𝞟" },
  "Ρ": { bold: "𝚸", italic: "𝛲", boldItalic: "𝜬", boldSans: "𝝦", boldItalicSans: "𝞠" },
  "Σ": { bold: "𝚺", italic: "𝛴", boldItalic: "𝜮", boldSans: "𝝨", boldItalicSans: "𝞢" },
  "Τ": { bold: "𝚻", italic: "𝛵", boldItalic: "𝜯", boldSans: "𝝩", boldItalicSans: "𝞣" },
  "Υ": { bold: "𝚼", italic: "𝛶", boldItalic: "𝜰", boldSans: "𝝪", boldItalicSans: "𝞤" },
  "Φ": { bold: "𝚽", italic: "𝛷", boldItalic: "𝜱", boldSans: "𝝫", boldItalicSans: "𝞥" },
  "Χ": { bold: "𝚾", italic: "𝛸", boldItalic: "𝜲", boldSans: "𝝬", boldItalicSans: "𝞦" },
  "Ψ": { bold: "𝚿", italic: "𝛹", boldItalic: "𝜳", boldSans: "𝝭", boldItalicSans: "𝞧" },
  "Ω": { bold: "𝛀", italic: "𝛺", boldItalic: "𝜴", boldSans: "𝝮", boldItalicSans: "𝞨" },
  "0": { bold: "𝟎", doubleStruck: "𝟘", boldSans: "𝟢", italicSans: "𝟬", monospace: "𝟶" },
  "1": { bold: "𝟏", doubleStruck: "𝟙", boldSans: "𝟣", italicSans: "𝟭", monospace: "𝟷" },
  "2": { bold: "𝟐", doubleStruck: "𝟚", boldSans: "𝟤", italicSans: "𝟮", monospace: "𝟸" },
  "3": { bold: "𝟑", doubleStruck: "𝟛", boldSans: "𝟥", italicSans: "𝟯", monospace: "𝟹" },
  "4": { bold: "𝟒", doubleStruck: "𝟜", boldSans: "𝟦", italicSans: "𝟰", monospace: "𝟺" },
  "5": { bold: "𝟓", doubleStruck: "𝟝", boldSans: "𝟧", italicSans: "𝟱", monospace: "𝟻" },
  "6": { bold: "𝟔", doubleStruck: "𝟞", boldSans: "𝟨", italicSans: "𝟲", monospace: "𝟼" },
  "7": { bold: "𝟕", doubleStruck: "𝟟", boldSans: "𝟩", italicSans: "𝟳", monospace: "𝟽" },
  "8": { bold: "𝟖", doubleStruck: "𝟠", boldSans: "𝟪", italicSans: "𝟴", monospace: "𝟾" },
  "9": { bold: "𝟗", doubleStruck: "𝟡", boldSans: "𝟫", italicSans: "𝟵", monospace: "𝟿" },
};
