import { BlockNode, DocumentNode, PropertyNode, TextNode } from "./ast.ts";

export function parse(text: string, isSnippet = false): DocumentNode {
  // LyX treats lines starting with '#' as comments. The conventional first line
  // is "#LyX 2.x created this file..." but any '#' comment is valid (e.g.,
  // files generated by gen_lfuns.py use "# gen_lfuns.py generated...").
  // We require at least one '#' comment line to guard against non-LyX input.
  if (!isSnippet && !text.trim().startsWith("#")) {
    throw new Error("Invalid LyX file format. Expected '#' comment header.");
  }
  const lines = text.split(/\r?\n/);
  const root: DocumentNode = { type: "document", children: [] };
  const stack: BlockNode[] = [];
  // Opening line (0-based, matching the 'at line N' convention of the
  // mismatched-end-tag error) of each open block, so an unclosed block can be
  // reported with a locatable line.
  const stackLine: number[] = [];

  let inOpaqueBlock = false;
  let opaqueTag = "";

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (inOpaqueBlock) {
      if (line === `\\end_${opaqueTag}`) {
        inOpaqueBlock = false;
        stack.pop();
        stackLine.pop();
      } else {
        stack[stack.length - 1].children.push({ type: "text", text: line });
      }
      continue;
    }

    const beginMatch = line.match(/^\\begin_([a-zA-Z0-9_]+)(?:\s+(.*))?$/);
    if (beginMatch) {
      const tag = beginMatch[1];
      const args = beginMatch[2];
      const block: BlockNode = { type: "block", tag, args, isBeginVariant: true, children: [] };
      
      if (stack.length > 0) {
        stack[stack.length - 1].children.push(block);
      } else {
        root.children.push(block);
      }
      stack.push(block);
      stackLine.push(i);

      if (tag === "preamble" || (tag === "inset" && (args === "Formula" || args === "ERT"))) {
        inOpaqueBlock = true;
        opaqueTag = tag;
      }
      continue;
    }

    const endMatch = line.match(/^\\end_([a-zA-Z0-9_]+)$/);
    if (endMatch) {
      const tag = endMatch[1];
      if (stack.length === 0 || stack[stack.length - 1].tag !== tag) {
        throw new Error(`Mismatched end tag: expected ${stack[stack.length - 1]?.tag}, got ${tag} at line ${i}`);
      }
      stack.pop();
      stackLine.pop();
      continue;
    }

    const propMatch = line.match(/^\\([a-zA-Z0-9_]+)(?:\s+(.*))?$/);
    if (propMatch) {
      const key = propMatch[1];
      const value = propMatch[2];
      
      // Handle special LyX blocks that don't use the \begin_ prefix
      if (key === "index" || key === "branch" || key === "modules") {
        const block: BlockNode = { type: "block", tag: key, args: value, isBeginVariant: false, children: [] };
        if (stack.length > 0) {
          stack[stack.length - 1].children.push(block);
        } else {
          root.children.push(block);
        }
        stack.push(block);
        stackLine.push(i);
        continue;
      }

      const prop: PropertyNode = { type: "property", key, value };
      if (stack.length > 0) {
        stack[stack.length - 1].children.push(prop);
      } else {
        root.children.push(prop);
      }
      continue;
    }

    const textNode: TextNode = { type: "text", text: line };
    if (stack.length > 0) {
      stack[stack.length - 1].children.push(textNode);
    } else {
      root.children.push(textNode);
    }
  }

  if (stack.length > 0) {
    throw new Error(
      `Unclosed tag: ${stack[stack.length - 1].tag} (opened at line ${stackLine[stackLine.length - 1]})`,
    );
  }

  return root;
}
